name: Update Toggl Time Tracking
on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:
jobs:
  update-toggl-tracking:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Start and End Dates for Current Month
        id: set_dates
        run: |
          FIRST_DAY_OF_MONTH=$(date -u -d "$(date +'%Y-%m-01')" +'%Y-%m-%d')
          LAST_DAY_OF_MONTH=$(date -u -d "$(date +'%Y-%m-01 +1 month -1 day')" +'%Y-%m-%d')
          echo "FIRST_DAY_OF_MONTH=$FIRST_DAY_OF_MONTH" >> $GITHUB_ENV
          echo "LAST_DAY_OF_MONTH=$LAST_DAY_OF_MONTH" >> $GITHUB_ENV

      - name: Fetch Toggl Time Data
        run: |
          curl -u "${{ secrets.TOGGL_API_TOKEN }}:api_token" \
               "https://api.track.toggl.com/reports/api/v2/summary?workspace_id=${{ secrets.TOGGL_WORKSPACE_ID }}&since=${FIRST_DAY_OF_MONTH}&until=${LAST_DAY_OF_MONTH}&project_ids=${{ secrets.PROJECT_ID }}&user_agent=your_email@example.com" \
               -o toggl_time.json

      - name: Generate SVG
        run: python generate_svg.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add toggl_time.json toggl_time.svg
          git commit -m "Update Toggl tracking data" || echo "No changes to commit"
          git push
